<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AssemblyName>J4JSoftware.FileUtilities</AssemblyName>
	  <RootNamespace>J4JSoftware.FileUtilities</RootNamespace>
	  <Nullable>enable</Nullable>
	  <Authors>Mark A. Olbert</Authors>
	  <Company>Jump for Joy Software</Company>
	  <Product>J4JSoftware Utilities for working with files and tabular data</Product>
	  <Description>a utility framework to simplify working with files and tabular data</Description>
	  <Copyright>© Mark A. Olbert all rights reserved</Copyright>
	  <Version>1.0.0.0</Version>
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>
	  <RepositoryUrl>https://github.com/markolbert/FileUtilities</RepositoryUrl>
	  <RepositoryType>git</RepositoryType>
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
	  <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	  <PackageReleaseNotes>initial release</PackageReleaseNotes>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageLicenseFile>license.md</PackageLicenseFile>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
		<PackageReference Include="NPOI" Version="2.7.5" />
		<PackageReference Include="System.Linq.Async" Version="7.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\GeneralUtilities\src\GeneralUtilities.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../readme.md" Pack="true" PackagePath="\" />
		<None Include="../license.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resource1.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource1.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resource1.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
